wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667155686.843567
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.8103124202682005
learning_rate:
  desc: null
  value: 0.05211591514506167
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 5
n_estimators:
  desc: null
  value: 858
reg_alpha:
  desc: null
  value: 1.19823274370227
reg_lambda:
  desc: null
  value: 2.683077042501399
