wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667154260.903379
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.7998636240029658
learning_rate:
  desc: null
  value: 0.15371915984446033
max_depth:
  desc: null
  value: 4
min_child_weight:
  desc: null
  value: 10
n_estimators:
  desc: null
  value: 958
reg_alpha:
  desc: null
  value: 2.893590073174453
reg_lambda:
  desc: null
  value: 1.9423211849275508
