wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667156299.064237
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.2705475450516703
learning_rate:
  desc: null
  value: 0.165069897329719
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 933
reg_alpha:
  desc: null
  value: 3.779591470678107
reg_lambda:
  desc: null
  value: 0.46690690548189784
