wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667155724.142613
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.4595009852630321
learning_rate:
  desc: null
  value: 0.08590583295746054
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 301
reg_alpha:
  desc: null
  value: 3.4933838584014634
reg_lambda:
  desc: null
  value: 0.2966795746713128
