wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667155670.95337
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.7743045148670195
learning_rate:
  desc: null
  value: 0.04924527935858913
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 9
n_estimators:
  desc: null
  value: 998
reg_alpha:
  desc: null
  value: 2.5531256968774216
reg_lambda:
  desc: null
  value: 3.80328729757347
