wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667158840.142375
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
    viz:
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      outlier_candidates:
        historyFieldSettings:
          key: outlier_candidates
          x-axis: _step
        id: wandb/outliers/v1
      residuals:
        historyFieldSettings:
          key: residuals
          x-axis: _step
        id: wandb/residuals_plot/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
gamma:
  desc: null
  value: 0.287904542854942
learning_rate:
  desc: null
  value: 0.09662062132535391
max_depth:
  desc: null
  value: 7
min_child_weight:
  desc: null
  value: 6
n_estimators:
  desc: null
  value: 776
reg_alpha:
  desc: null
  value: 1.8788655123255416
reg_lambda:
  desc: null
  value: 3.130767214134446
