wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667153115.407493
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.20246298765922788
learning_rate:
  desc: null
  value: 0.12349813025398254
max_depth:
  desc: null
  value: 8
min_child_weight:
  desc: null
  value: 8
n_estimators:
  desc: null
  value: 254
reg_alpha:
  desc: null
  value: 3.605389806012732
reg_lambda:
  desc: null
  value: 1.9324269036543735
