wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667155742.160888
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.5899963743286805
learning_rate:
  desc: null
  value: 0.17935361590128543
max_depth:
  desc: null
  value: 7
min_child_weight:
  desc: null
  value: 5
n_estimators:
  desc: null
  value: 965
reg_alpha:
  desc: null
  value: 0.7152259739473904
reg_lambda:
  desc: null
  value: 0.2037261405211756
