wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667156187.407044
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
gamma:
  desc: null
  value: 0.8813157507921134
learning_rate:
  desc: null
  value: 0.0030655120376972224
max_depth:
  desc: null
  value: 9
min_child_weight:
  desc: null
  value: 9
n_estimators:
  desc: null
  value: 723
reg_alpha:
  desc: null
  value: 3.337694682308858
reg_lambda:
  desc: null
  value: 0.3963291939439684
