wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1667157204.715341
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      - 37
      4: 3.8.0
      5: 0.13.4
      8:
      - 1
      - 5
    viz:
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      outlier_candidates:
        historyFieldSettings:
          key: outlier_candidates
          x-axis: _step
        id: wandb/outliers/v1
      residuals:
        historyFieldSettings:
          key: residuals
          x-axis: _step
        id: wandb/residuals_plot/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
gamma:
  desc: null
  value: 0.8945566834497739
learning_rate:
  desc: null
  value: 0.049544933337289696
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 485
reg_alpha:
  desc: null
  value: 1.4898752742129238
reg_lambda:
  desc: null
  value: 2.523415550598697
